services:
  firestore:
    image: evolutecx/firebase-emulator:latest
    container_name: firestore-emulator
    ports:
      - "4000:4000"   # Emulator UI
      - "8080:8080"   # Firestore
      - "9150:9150"   # WebSocket (UI)
      - "4400:4400"   # Emulator Hub
    environment:
      - FB_PROJECT_ID=demo-project
    volumes:
      # 1. Mount host's firebase.json into the container so emulator reads correct config
      - ./firebase.json:/firebase/firebase.json
      # 2. Mount host's firebase-data folder into container's /firebase/data
      - ./firebase-data:/firebase/data
    restart: unless-stopped